# Generated by Django 2.2.9 on 2020-02-17 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPalavrasBloqueadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('palavra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Palavra')),
            ],
            options={
                'verbose_name': 'Lista palavra bloqueada',
                'verbose_name_plural': 'Lista palavras bloqueadas',
            },
        ),
    ]
