# Generated by Django 2.2.9 on 2020-08-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_listaemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Log e-mail enviado (Pedido Uniforme)', 'verbose_name_plural': 'Log e-mails enviados (Pedido Uniforme)'},
        ),
        migrations.AlterModelOptions(
            name='listaemail',
            options={'verbose_name': 'Lista de Email (SME)', 'verbose_name_plural': 'Lista de Emails (SME)'},
        ),
    ]
