# Generated by Django 2.2.9 on 2020-08-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailmercadopago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmercadopago',
            options={'verbose_name': 'E-mail mercado pago', 'verbose_name_plural': 'E-mail mercado pago'},
        ),
    ]
