# Generated by Django 2.2.9 on 2020-08-18 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200812_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEmailMercadoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado?')),
                ('enviar_para', models.CharField(blank=True, max_length=255, null=True, verbose_name='Enviar Para')),
                ('assunto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('csv', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arquivo CSV')),
            ],
            options={
                'verbose_name': 'Log e-mail enviado (Pedido Uniforme)',
                'verbose_name_plural': 'Log e-mails enviados (Pedido Uniforme)',
            },
        ),
    ]
