# Generated by Django 2.2.9 on 2020-08-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_logemailmercadopago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logemailmercadopago',
            options={'verbose_name': 'Log e-mail enviado (Mercado Pago)', 'verbose_name_plural': 'Log e-mails enviados (Mercado Pago)'},
        ),
    ]
