# Generated by Django 2.2.9 on 2020-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200223_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome_escola',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Escola'),
        ),
    ]
