version: '3.1'
services:

  db:
    image: postgres:11.2-alpine
    container_name: aluno-postgres-local
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345qw
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: aluno
      PGPASSWORD: 12345qw
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    # ports:
    #   - 5433:5432

  redis:
    image: redis:5.0.0-alpine
    container_name: aluno-redis-local
    restart: always
    # ports:
    #   - "6379:6379"

  backend:
    container_name: alunos-backend
    build: .
    env_file: .env
    ports:
      - 8001:8000
    volumes:
      - ./staticfiles:/code/staticfiles
    depends_on:
      - db
      - redis
    links:
      - db:db

networks:
  default:
    external:
      name: aluno-network

