# Generated by Django 2.2.9 on 2020-01-31 21:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vinculo', models.CharField(choices=[('MAE', 'Mãe'), ('PAI', 'Pai'), ('RESPONSAVEL_LEGAL', 'Responsável Legal'), ('ALUNO_MAIOR_IDADE', 'Aluno Maior de Idade')], default='RESPONSAVEL_LEGAL', max_length=15, verbose_name='status')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('ddd_celular_responsavel', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD Tel. Celular')),
                ('celular', models.CharField(blank=True, max_length=9, null=True, verbose_name='Número Tel. Celular')),
                ('ddd_telefone_fixo', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD Tel. Fixo')),
                ('telefone_fixo', models.CharField(blank=True, max_length=9, null=True, verbose_name='Numero Tel. Fixo')),
                ('ddd_telefone_comercial', models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD Tel. Comercial')),
                ('telefone_comercial', models.CharField(blank=True, max_length=9, null=True, verbose_name='Numero Tel. Comercial')),
                ('ramal_telefone_comercial', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ramal')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe do Responsável')),
                ('status', models.CharField(choices=[('ATUALIZADO', 'Atualizado'), ('DIVERGENTE', 'Divergente'), ('ERRO', 'Erro')], default='ATUALIZADO', max_length=15, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Responsavel',
                'verbose_name_plural': 'Responsaveis',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_eol', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Código EOL do Aluno')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Alunos', to='alunos.Responsavel')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
