# Generated by Django 2.2.9 on 2020-02-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsavel',
            old_name='ddd_celular_responsavel',
            new_name='ddd_celular',
        ),
    ]
