# Generated by Django 2.2.9 on 2020-02-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_auto_20200202_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='ddd_telefone_comercial',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='ddd_telefone_fixo',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='ramal_telefone_comercial',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='telefone_comercial',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='telefone_fixo',
        ),
    ]
