# Generated by Django 2.2.9 on 2020-02-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_auto_20200207_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='status',
            field=models.CharField(choices=[('ATUALIZADO', 'Atualizado'), ('PENDENTE', 'Pendente'), ('DIVERGENTE', 'Divergente'), ('ERRO', 'Erro')], default='PENDENTE', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='vinculo',
            field=models.CharField(choices=[('MAE', 'Mãe'), ('PAI', 'Pai'), ('RESPONSAVEL_LEGAL', 'Responsável Legal'), ('ALUNO_MAIOR_IDADE', 'Aluno Maior de Idade')], default='RESPONSAVEL_LEGAL', max_length=20, verbose_name='Vínculo'),
        ),
    ]
