# Generated by Django 2.2.9 on 2020-02-17 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0009_auto_20200210_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='atualizado_na_escola',
            field=models.BooleanField(default=False, verbose_name='Atualizado na Escola'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='codigo_dre',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código EOL da DRE'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='codigo_escola',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código EOL da Escola'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='servidor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código EOL da Escola'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='codigo_eol',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código EOL do Aluno'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Necessário 9 digitos', regex='^\\d{9}$')], verbose_name='Número Tel. Celular'),
        ),
    ]
