# Generated by Django 2.2.9 on 2020-02-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_auto_20200217_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='servidor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RF do Servidor'),
        ),
    ]
