# Generated by Django 2.2.9 on 2020-02-17 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0013_auto_20200217_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Necessário 11 digitos', regex='^\\d{11}$')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Não é permitido número', regex='^[a-zA-Z]+$')], verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='vinculo',
            field=models.IntegerField(choices=[(1, 'Mãe'), (2, 'Pai'), (3, 'Responsável Legal'), (4, 'Aluno Maior de Idade')], default=3, max_length=1, verbose_name='Vínculo'),
        ),
    ]
