# Generated by Django 2.2.9 on 2020-02-17 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0014_auto_20200217_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Necessário 9 digitos', regex='^\\d{9}$')], verbose_name='Número Celular'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Necessário 11 digitos', regex='^\\d{11}$')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='ddd_celular',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='DDD Celular'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='status',
            field=models.CharField(choices=[('ATUALIZADO_EOL', 'Atualizado no EOL'), ('ATUALIZADO_VALIDO', 'Atualizado e validado (Aguardando Envio EOL)'), ('DIVERGENTE', 'Divergente'), ('DESATUALIZADO', 'Desatualizado'), ('PENDENCIA_RESOLVIDA', 'Pendência Resolvida na Escola')], default='ATUALIZADO_VALIDO', max_length=15, verbose_name='status'),
        ),
    ]
