# Generated by Django 2.2.9 on 2020-02-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0015_auto_20200217_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='codigo_eol_aluno',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código EOL do Aluno'),
        ),
    ]
