# Generated by Django 2.2.9 on 2020-02-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0016_responsavel_codigo_eol_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='status',
            field=models.CharField(choices=[('ATUALIZADO_EOL', 'Atualizado no EOL'), ('ATUALIZADO_VALIDO', 'Atualizado e validado (Aguardando Envio EOL)'), ('DIVERGENTE', 'Divergente'), ('DESATUALIZADO', 'Desatualizado'), ('PENDENCIA_RESOLVIDA', 'Pendência Resolvida na Escola')], default='ATUALIZADO_VALIDO', max_length=20, verbose_name='status'),
        ),
    ]
