# Generated by Django 2.2.9 on 2020-02-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0018_auto_20200217_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='status',
            field=models.CharField(choices=[('ATUALIZADO_EOL', 'Atualizado no EOL'), ('ATUALIZADO_VALIDO', 'Atualizado e validado (Aguardando Envio EOL)'), ('DIVERGENTE', 'Divergente'), ('DESATUALIZADO', 'Desatualizado'), ('PENDENCIA_RESOLVIDA', 'Pendência Resolvida na Escola')], default='ATUALIZADO_VALIDO', max_length=30, verbose_name='status'),
        ),
    ]
