# Generated by Django 2.2.9 on 2020-02-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0019_auto_20200220_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='status',
            field=models.CharField(choices=[('ATUALIZADO_EOL', 'Cadastro Atualizado no EOL'), ('ATUALIZADO_VALIDO', 'Cadastro Atualizado e validado (Aguardando Envio EOL)'), ('DIVERGENTE', 'Cadastro Divergente'), ('DESATUALIZADO', 'Cadastro Desatualizado'), ('PENDENCIA_RESOLVIDA', 'Cadastro com Pendência Resolvida')], default='ATUALIZADO_VALIDO', max_length=30, verbose_name='status'),
        ),
    ]
