# Generated by Django 2.2.9 on 2020-03-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0021_auto_20200226_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='nao_possui_celular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='nao_possui_email',
            field=models.BooleanField(default=False),
        ),
    ]
