# Generated by Django 2.2.9 on 2020-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0022_auto_20200313_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='pendencia_resolvida',
            field=models.BooleanField(default=False),
        ),
    ]
