# Generated by Django 2.2.9 on 2020-08-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0023_responsavel_pendencia_resolvida'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='enviado_para_mercado_pago',
            field=models.BooleanField(default=False),
        ),
    ]
