# Generated by Django 2.2.9 on 2020-08-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0024_responsavel_enviado_para_mercado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='data_envio_mercado_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Envio Mercado Pago'),
        ),
    ]
