# Generated by Django 2.2.9 on 2020-08-27 20:55

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0025_responsavel_data_envio_mercado_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetornoMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_eol', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Código EOL do Aluno')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Necessário 11 digitos', regex='^\\d{11}$')], verbose_name='CPF')),
                ('status', models.IntegerField(choices=[(5, 'Responsável com mais de um e-mail informado'), (7, 'Crédito já liberado para outro CPF'), (8, 'CPF Bloqueado'), (9, 'Crédito Concedido'), (10, 'E-mail Inválido'), (11, 'CPF Inválido')], verbose_name='Status')),
                ('mensagem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mensagem')),
                ('data_ocorrencia', models.DateField(blank=True, null=True, verbose_name='Data de Ocorrencia no MP')),
                ('registro_processado', models.BooleanField(default=False, verbose_name='Registro Processado?')),
            ],
            options={
                'verbose_name': 'Retorno do Mercado Pago',
                'verbose_name_plural': 'Retornos do Mercado Pago',
            },
        ),
    ]
