# Generated by Django 2.2.9 on 2020-09-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0026_retornomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retornomp',
            name='status',
            field=models.IntegerField(choices=[(5, 'Responsável com mais de um e-mail informado'), (7, 'Crédito já liberado para outro CPF'), (9, 'Crédito Concedido'), (10, 'E-mail Inválido'), (11, 'CPF Inválido')], verbose_name='Status'),
        ),
    ]
