# Generated by Django 2.2.9 on 2020-09-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0028_auto_20200902_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='status',
            field=models.CharField(choices=[('ATUALIZADO_EOL', 'Cadastro Atualizado no EOL'), ('ATUALIZADO_VALIDO', 'Cadastro Atualizado e validado'), ('DIVERGENTE', 'Cadastro Divergente'), ('DESATUALIZADO', 'Cadastro Desatualizado'), ('PENDENCIA_RESOLVIDA', 'Cadastro com Pendência Resolvida'), ('CREDITO_CONCEDIDO', 'Cadastro com Crédito Concedido'), ('INCONSISTENCIA_RESOLVIDA', 'Cadastro com inconsistência resolvida'), ('CPF_INVALIDO', 'Cadastro com CPF inválido'), ('EMAIL_INVALIDO', 'Cadastro com e-mail inválido'), ('MULTIPLOS_EMAILS', 'Cadastro com mais de um e-mail cadastrado')], default='ATUALIZADO_VALIDO', max_length=30, verbose_name='status'),
        ),
    ]
