# Generated by Django 2.2.9 on 2020-09-10 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0029_auto_20200909_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='retornomp',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retornos', to='alunos.Responsavel'),
        ),
    ]
