# Generated by Django 2.2.9 on 2020-09-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0030_retornomp_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='responsavel_alterado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retornomp',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Está ativo?'),
        ),
    ]
