# Generated by Django 2.2.9 on 2020-09-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0033_auto_20200917_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='logerroatualizacaoeol',
            name='resolvido',
            field=models.BooleanField(default=False, verbose_name='Erro Resolvido?'),
        ),
    ]
